### ISSUE TITLE
Two errors when deploying on Apple TV4

### ISSUE THREAD

**Issue by csujedihy** [XIAZY/BiliBite#2]
Under Xcode 8.3

1. Wrong path setting on your BiliBite group which cause Xcode unable to locate files.
2. ~~Failed to run on a real Apple TV4 after successful building.~~

```
2017-08-06 19:39:04.870052-0500 BiliBite[640:173453] [System] App Context Failed with Error: Error Domain=ITMLKitErrorDomain Code=101 "(null)" UserInfo={ITMLKitErrorHTTPStatus=0}
appController(_:didFail:) invoked with error: Error Domain=TVMLKitErrorDomain Code=3 "(null)"

```

**Comment by csujedihy** [comment]
Works on a simulator but not on the device (ATV4).

**Comment by XIAZY** [comment]
I just built it yesterday and it works as expected in an ATV 4. Allow all arbitrary HTTP loads should solve this problem.

**Comment by csujedihy** [comment]
Works good after path setting is fixed.

**Comment by XIAZY** [comment]
I'll fix the path problem in the next commit, or you can submit a PR if you would like

**Comment by csujedihy** [comment]
Thanks.
